# pull.psm1 - Pull command for WinSpec
# Captures system state and saves to a configuration file
# Replaces: export.psm1, init.psm1

# Import dependent modules
Import-Module (Join-Path $PSScriptRoot "logging.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "state.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "utils.psm1") -Force

# =============================================================================
# PULL COMMAND - Export system state to config
# =============================================================================

function Invoke-Pull {
    <#
    .SYNOPSIS
        Pulls system state into a configuration file.
    .DESCRIPTION
        Captures current system state and saves it to a config file.
        Combines functionality of export and init commands.
    .PARAMETER Output
        Path to write the configuration file.
    .PARAMETER Providers
        Array of providers to include.
    .PARAMETER Format
        Output format: ps1 or json.
    .PARAMETER Interactive
        Enable interactive selection of items.
    .PARAMETER Template
        Include comments and structure.
    .PARAMETER Minimal
        Only include non-default settings.
    .PARAMETER DryRun
        Preview without writing.
    .PARAMETER Name
        Configuration name.
    .PARAMETER Description
        Configuration description.
    .OUTPUTS
        Hashtable representing the captured state.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [Parameter(Mandatory = $false)]
        [string]$Output,
        
        [Parameter(Mandatory = $false)]
        [string[]]$Providers = @(),
        
        [Parameter(Mandatory = $false)]
        [ValidateSet("ps1", "json")]
        [string]$Format = "ps1",
        
        [Parameter(Mandatory = $false)]
        [switch]$Interactive,
        
        [Parameter(Mandatory = $false)]
        [switch]$Template,
        
        [Parameter(Mandatory = $false)]
        [switch]$Minimal,
        
        [Parameter(Mandatory = $false)]
        [string]$Name = "WinSpec Configuration",
        
        [Parameter(Mandatory = $false)]
        [string]$Description = "Generated by WinSpec"
    )
    
    Write-LogHeader -Title "WinSpec Pull"
    
    # Resolve output path
    $outputPath = Resolve-ConfigPath -OutputPath $Output
    if (-not $outputPath) {
        Write-Log -Level "ERROR" -Message "Could not resolve output path"
        return $null
    }
    
    Write-Log -Level "INFO" -Message "Capturing system state..."
    
    # Capture system state
    $systemState = Get-SystemState -Providers $Providers
    
    if (-not $systemState -or $systemState.Count -eq 0) {
        Write-Log -Level "WARN" -Message "No system state captured"
        return $null
    }
    
    # Show summary
    Write-Log -Level "INFO" -Message "Captured state for providers: $($systemState.Keys -join ', ')"
    
    # Add metadata
    $config = @{
        Name = $Name
        Description = $Description
    }
    
    # Merge captured state into config
    foreach ($key in $systemState.Keys) {
        $config[$key] = $systemState[$key]
    }
    
    # Interactive mode - filter items
    if ($Interactive) {
        $config = Invoke-PullInteractive -Config $config
    }
    
    # Minimal mode - filter defaults
    if ($Minimal) {
        $config = Invoke-PullMinimal -Config $config
    }
    
    # Write to file
    if ($outputPath) {
        if ($PSCmdlet.ShouldProcess($outputPath, 'Save configuration')) {
            $success = Save-Configuration -Config $config -Path $outputPath
            if ($success) {
                Write-Log -Level "OK" -Message "Configuration saved to: $outputPath"
            }
            else {
                Write-Log -Level "ERROR" -Message "Failed to save configuration"
                return $null
            }
        }
    }
    
    return $config
}

function Invoke-PullInteractive {
    <#
    .SYNOPSIS
        Interactive selection of config items.
    #>
    param(
        [hashtable]$Config
    )
    
    $filteredConfig = @{
        Name = $Config.Name
        Description = $Config.Description
    }
    
    Write-Host ""
    Write-Host "=== Interactive Selection ===" -ForegroundColor Cyan
    Write-Host "Press Enter to include item, 's' to skip all" -ForegroundColor Gray
    
    foreach ($key in $Config.Keys | Where-Object { $_ -notin @("Name", "Description") }) {
        $value = $Config[$key]
        
        Write-Host ""
        $response = Read-Host "Include $key? [Y/n/s]"
        
        if ($response -eq "s") { break }
        if (-not $response -or $response -match '^[Yy]') {
            $filteredConfig[$key] = $value
            Write-Host "  Included" -ForegroundColor Green
        }
        else {
            Write-Host "  Skipped" -ForegroundColor Gray
        }
    }
    
    return $filteredConfig
}

function Invoke-PullMinimal {
    <#
    .SYNOPSIS
        Filters config to non-default settings.
    #>
    param(
        [hashtable]$Config
    )
    
    $filteredConfig = @{
        Name = $Config.Name
        Description = $Config.Description
    }
    
    # For now, include all - could be enhanced with default value checking
    foreach ($key in $Config.Keys | Where-Object { $_ -notin @("Name", "Description") }) {
        $value = $Config[$key]
        
        # Skip empty providers
        if ($value -is [hashtable] -and $value.Count -eq 0) {
            continue
        }
        
        $filteredConfig[$key] = $value
    }
    
    return $filteredConfig
}

# Alias for backward compatibility
Set-Alias -Name "Export-SystemState" -Value "Invoke-Pull" -Scope Global

Export-ModuleMember -Function @(
    "Invoke-Pull"
)
