# pull.psm1 - Pull command for WinSpec
# Captures system state and saves to a configuration file
# Replaces: export.psm1, init.psm1

# Import dependent modules
Import-Module (Join-Path $PSScriptRoot "logging.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "utils.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "state.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "merge.psm1") -Force

# =============================================================================
# PULL COMMAND - Export system state to config
# =============================================================================

function Invoke-Pull {
    [CmdletBinding(SupportsShouldProcess)]
    param(
        [string]$Output,

        [hashtable]$Spec,

        [string[]]$Providers,

        [switch]$Apply,

        [switch]$Minimal,

        [switch]$DryRun,

        [switch]$Interactive,

        [string]$ConfigPath,

        [string]$Name = "WinSpec Configuration",
        [string]$Description = "Generated by WinSpec"
    )

    Write-LogHeader -Title "WinSpec Pull"

    $effectiveProviders = $Providers
    if (-not $effectiveProviders -and $Spec -and $Spec.ContainsKey("Providers")) {
        $effectiveProviders = $Spec.Providers
    }

    if ($effectiveProviders) {
        Write-Log INFO "Using providers: $($effectiveProviders -join ', ')"
    }

    Write-Log INFO "Capturing system state..."
    $systemState = Get-SystemState -Providers $effectiveProviders -ConfigPath $ConfigPath

    if (-not $systemState -or $systemState.Count -eq 0) {
        Write-Log WARN "No system state captured"
        return @{ Success = $false; Reason = "NoStateCaptured" }
    }
    Write-Log INFO "Captured providers: $($systemState.Keys -join ', ')"
    $config = @{
        Name        = $Name
        Description = $Description
    }

    foreach ($k in $systemState.Keys) {
        $config[$k] = $systemState[$k]
    }
    if ($Output -and (Test-Path $Output)) {
        if (-not $Apply) {
            Write-Log ERROR "Spec already exists. Use -Apply to merge."
            return @{ Success = $false; Reason = "OutputExists"; Path = $Output }
        }

        Write-Log INFO "Merging captured state"
        $merge = Merge-Configuration `
            -Base $Spec `
            -Incoming $config `
            -Strategy auto `
            -Interactive:$Interactive

        if (-not $merge.Success) {
            Write-Log ERROR "Merge failed with unresolved conflicts"
            return @{ Success = $false; Reason = "MergeFailed"; Merge = $merge }
        }

        $config = $merge.Merged
    }

    if ($Minimal) {
        $config = Invoke-PullMinimal $config
    }

    if ($Output -and -not $DryRun) {
        if ($PSCmdlet.ShouldProcess($Output,"Save spec")) {
            $null = Save-Configuration `
                -Config $config `
                -Path $Output
        }
    }
    elseif ($Output -and $DryRun) {
        Write-Log INFO "DryRun: would save spec to $Output"
    }

    return $config
}

function Invoke-PullMinimal {
    param(
        [hashtable]$Config
    )

    $result = @{}

    foreach ($k in $Config.Keys) {
        $value = $Config[$k]
        if ($null -eq $value) { continue }
        if ($value -is [hashtable] -and $value.Count -eq 0) { continue }
        if ($value -is [array] -and $value.Count -eq 0) { continue }
        $result[$k] = $value
    }

    return $result
}

Export-ModuleMember -Function @(
    "Invoke-Pull"
)
