# pull.psm1 - Pull command for WinSpec
# Captures system state and saves to a configuration file
# Replaces: export.psm1, init.psm1

# Import dependent modules
Import-Module (Join-Path $PSScriptRoot "logging.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "state.psm1") -Force
Import-Module (Join-Path $PSScriptRoot "utils.psm1") -Force

# =============================================================================
# PULL COMMAND - Export system state to config
# =============================================================================

function Invoke-Pull {

    <#
.SYNOPSIS
    Initialize, pull, or merge a WinSpec configuration.

.DESCRIPTION
    Captures system state and writes it as a spec file.
    If the output file exists, -Apply is required to merge.

.PARAMETER Spec
    Existing spec object used for provider hints or merging.

.PARAMETER Output
    Path to write the spec file.

.PARAMETER Providers
    Providers to capture. Overrides spec providers.

.PARAMETER Apply
    Merge with existing spec if output file already exists.

.PARAMETER Format
    Output format: ps1 or json.

.PARAMETER Interactive
    Interactive item selection.

.PARAMETER Minimal
    Exclude empty/default values.

.PARAMETER Name
    Spec name.

.PARAMETER Description
    Spec description.
#>

    [CmdletBinding(SupportsShouldProcess)]
    param(
        [hashtable]$Spec,

        [string]$Output,

        [switch]$Apply,

        [string[]]$Providers,

        [ValidateSet("ps1", "json")]
        [string]$Format = "ps1",

        [switch]$Interactive,
        [switch]$Minimal,
        [switch]$NoCache = $False,

        [string]$Name = "WinSpec Configuration",
        [string]$Description = "Generated by WinSpec"
    )

    Write-LogHeader -Title "WinSpec Pull"

    $effectiveProviders = @()

    if ($Providers) {
        $effectiveProviders = $Providers
    }
    elseif ($Spec -and $Spec.ContainsKey("Providers")) {
        $effectiveProviders = $Spec.Providers
    }
    if ($effectiveProviders.Count -gt 0) {
        Write-Log INFO "Using providers: $($effectiveProviders -join ', ')"
    }

    $outputPath = $Output
    if ((Test-Path $outputPath) -and -not $Apply) {
        Write-Log ERROR "Output file already exists. Use -Apply to merge."
        return
    }

    Write-Log INFO "Capturing system state..."

    $systemState = Get-SystemState -Providers $effectiveProviders -NoCache:$NoCache
    if (-not $systemState -or $systemState.Count -eq 0) {
        Write-Log WARN "No system state captured"
        return
    }
    Write-Log INFO "Captured providers: $($systemState.Keys -join ', ')"

    $config = @{
        Name        = $Name
        Description = $Description
    }

    $config += $systemState

    if ($Apply -and $Spec) {
        Write-Log INFO "Merging with existing spec"
        try {
            $config = Merge-SystemState `
                -SystemState $systemState `
                -SpecState $Spec

            $config.Name = $Name
            $config.Description = $Description
        }
        catch {
            Write-Log WARN "Merge failed: $($_.Exception.Message)"
        }
    }

    if ($Interactive) {
        $config = Invoke-PullInteractive $config
    }
    if ($Minimal) {
        $config = Invoke-PullMinimal $config
    }

    if ($outputPath) {
        if ($PSCmdlet.ShouldProcess($outputPath, "Save spec")) {
            $null = Save-Configuration `
                -Config $config `
                -Path $outputPath `
                -Format $Format
        }
    }

    return $config
}

function Invoke-PullInteractive {
    <#
    .SYNOPSIS
        Interactive selection of config items.
    #>
    param(
        [hashtable]$Config
    )
    
    $filteredConfig = @{
        Name        = $Config.Name
        Description = $Config.Description
    }
    
    Write-LogHeader -Title "Interactive SelectionWinSpec Pull"
    Write-Log "Press Enter to include item, 's' to skip all" -Level APPLIED 
    
    foreach ($key in $Config.Keys | Where-Object { $_ -notin @("Name", "Description") }) {
        $value = $Config[$key]
        
        Write-Host ""
        $response = Read-Host "Include $key? [Y/n/s]"
        
        if ($response -eq "s") { break }
        if (-not $response -or $response -match '^[Yy]') {
            $filteredConfig[$key] = $value
            Write-Log "  Included" -Level INFO 
        }
        else {
            Write-Log "  Skipped" -Level INFO 
        }
    }
    
    return $filteredConfig
}

function Invoke-PullMinimal {
    <#
    .SYNOPSIS
        Filters config to non-default settings.
    #>
    param(
        [hashtable]$Config
    )
    
    $filteredConfig = @{
        Name        = $Config.Name
        Description = $Config.Description
    }
    
    # For now, include all - could be enhanced with default value checking
    foreach ($key in $Config.Keys | Where-Object { $_ -notin @("Name", "Description") }) {
        $value = $Config[$key]
        # Skip empty providers
        if ($value -is [hashtable] -and $value.Count -eq 0) {
            continue
        }
        $filteredConfig[$key] = $value
    }
    
    return $filteredConfig
}

# Alias for backward compatibility
Set-Alias -Name "Export-SystemState" -Value "Invoke-Pull" -Scope Global

Export-ModuleMember -Function @(
    "Invoke-Pull"
)
