name: Mirror to Codeberg

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: yesolutions/mirror-action@1708f16cdb28634fd3ba10c5c79abc91f5578a14 # v0.7.0
        with:
          REMOTE: ssh://git@codeberg.org/nostalgia/winspec.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          GIT_PUSH_ARGS: "--force --tags"
