name: Mirror to Codeberg

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: ssh://git@codeberg.org/nostalgia/winspec.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.CODEBERG }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          GIT_PUSH_ARGS: "--force --tags"